### ISSUE TITLE
"raises when password or salt is nil to hash_password" test fails

### ISSUE THREAD

**Issue by nallwhy** [riverrun/pbkdf2_elixir#16]
``` shell
$ mix test test/base_test.exs:198

Excluding tags: [:test]
Including tags: [line: "198"]



  1) test raises when password or salt is nil to hash_password (Pbkdf2.BaseTest)
     test/base_test.exs:198
     Expected exception ErlangError but got ArgumentError (errors were found at the given arguments:
     
       * 1st argument: not an iodata term
     )
     code: assert_raise ErlangError, fn ->
     stacktrace:
       :erlang.iolist_to_binary(nil)
       (crypto 5.0.2) crypto.erl:599: :crypto.mac/4
       (pbkdf2_elixir 1.4.1) lib/pbkdf2/base.ex:96: Pbkdf2.Base.do_create_hash/7
       (pbkdf2_elixir 1.4.1) lib/pbkdf2/base.ex:49: Pbkdf2.Base.hash_password/3
       test/base_test.exs:200: (test)



Finished in 0.1 seconds (0.00s async, 0.1s sync)
11 tests, 1 failure, 10 excluded

Randomized with seed 136421
```

```elixir
  test "raises when password or salt is nil to hash_password" do
    if System.otp_release() >= "22" do
      assert_raise ErlangError, fn ->
        Base.hash_password(nil, "somesalt")
      end
    else
      assert_raise ArgumentError, fn ->
        Base.hash_password(nil, "somesalt")
      end
    end

    assert_raise ArgumentError, fn ->
      Base.hash_password("password", nil)
    end
  end
```

`ErlangError` normalizes erlang `:badarg` to `ArgumentError`.
I checked the error of `iolist_to_binary(nil).` on OTP 21, 22, 23, 24, but all throws `:badarg`, so that test should raises `ArgumentError` not `ErlangError`.

**Comment by riverrun** [comment]
Fixed - finally - in v1.4.2 (2022-01-19). Thanks for letting me know.
